vich_uploader:
    db_driver: orm
    mappings:
        file:
            uri_prefix: /ressources/products
            upload_destination: '%kernel.project_dir%/ressources/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true
