version: "3.7"

services:
  
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 10302:80
    networks:
      - symfony

  fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:root@db/soundplugs
    volumes:
      - ./:/var/www/project/:cached
    networks:
      - symfony

  db:
    image: mariadb:10.2.29
    ports:
      - "3317:3306"
    environment:
      - MYSQL_DATABASE=soundplugs
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
    networks:
      - symfony

networks:
  symfony:
    driver: bridge